#cloud-config
# vim: syntax=yaml
#


hostname: "$TEMPLATE_HOSTNAME"
manage_etc_hosts: true

users:
  - name: r9s
    gecos: "Raspbernetes User"
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: "/bin/bash"
    groups: "users,docker,video,input"
    plain_text_passwd: "r9s"
    lock_passwd: false
    ssh_pwauth: false
    ssh_authorized_keys:
      - "$TEMPLATE_CURRENT_SSH_KEY"

