#cloud-config

hostname: "$TEMPLATE_HOSTNAME"
manage_etc_hosts: true

users:
  - name: r9s
    gecos: "Raspbernetes User"
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: "/bin/bash"
    groups: "users,docker,video,input"
    plain_text_passwd: "r9s"
    ssh_authorized_keys:
      - "$TEMPLATE_CURRENT_SSH_KEY"
    lock_passwd: false
    ssh_pwauth: false
    chpasswd: { expire: false }
